# Generated by Django 4.1.7 on 2023-06-23 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("garagem_marcus", "0002_veiculo_descricao_alter_veiculo_ano_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="veiculo",
            name="acessorios",
            field=models.ManyToManyField(
                related_name="veiculos", to="garagem_marcus.acessorio"
            ),
        ),
    ]
