# Generated by Django 4.1.7 on 2023-05-19 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garagem_marcus', '0004_rename_cor_core_veiculo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrição', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='veiculo',
            old_name='cor',
            new_name='Cor',
        ),
    ]
