# Generated by Django 4.1.7 on 2023-08-30 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
        ('garagem_marcus', '0004_alter_marca_options_alter_marca_nacionalidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='capa',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='uploader.image'),
        ),
        migrations.AlterField(
            model_name='marca',
            name='nacionalidade',
            field=models.CharField(max_length=50),
        ),
    ]
