# Generated by Django 4.1.7 on 2023-09-04 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
        ('garagem_marcus', '0005_veiculo_capa_alter_marca_nacionalidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veiculo',
            name='capa',
        ),
        migrations.AddField(
            model_name='veiculo',
            name='capa',
            field=models.ManyToManyField(related_name='+', to='uploader.image'),
        ),
    ]
