# Generated by Django 4.1.7 on 2023-05-19 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garagem_marcus', '0006_alter_veiculo_cor_alter_veiculo_categoria_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='veiculo',
            old_name='Cor',
            new_name='cor',
        ),
    ]
