# Generated by Django 4.1.7 on 2023-10-02 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garagem_marcus', '0006_remove_veiculo_capa_veiculo_capa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acessorio',
            options={'verbose_name': 'Acessório', 'verbose_name_plural': 'Acessórios'},
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='veiculo',
            options={'verbose_name': 'veículo', 'verbose_name_plural': 'veículos'},
        ),
        migrations.RenameField(
            model_name='veiculo',
            old_name='capa',
            new_name='imagem',
        ),
        migrations.RemoveField(
            model_name='acessorio',
            name='descrição',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='veiculo',
        ),
        migrations.RemoveField(
            model_name='marca',
            name='nacionalidade',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='marca',
        ),
        migrations.AddField(
            model_name='acessorio',
            name='descricao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='descricao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='ano',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='descricao',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modelos', to='garagem_marcus.categoria')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modelos', to='garagem_marcus.marca')),
            ],
            options={
                'verbose_name': 'Modelo',
                'verbose_name_plural': 'Modelos',
            },
        ),
        migrations.AddField(
            model_name='veiculo',
            name='modelo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='veiculos', to='garagem_marcus.modelo'),
            preserve_default=False,
        ),
    ]
